
name: CI

on:
  push:
    branches: [ scraper ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: install linters
        run: sudo apt-get install -y cppcheck
        
      - name: install valgrind
        run: sudo apt install valgrind
        
      - name: install gcovr and lcov
        run: |
          sudo apt install gcovr
          sudo apt install lcov
          
      - name: run linters
        run: cd archiver/src && cppcheck *.cpp
        
      - name: build
        run: |
          cd archiver
          mkdir build
          cd build
          cmake ..
          make
          
      - name: test https_client lib
        run: |
          cd archiver
          cd build
          valgrind --leak-check=full ./test/https_socket_test_tests 

